services:
  # Conatiner do Front
  front:
    build: ./front
    container_name: front_container
    ports:
      - "4200:4200"
    depends_on:
      - back

  # Container Back
  back:
    build: ./back
    container_name: back_container
    ports:
      - "3000:3000"
    volumes:
      - ./back:/usr/src/app
    depends_on:
      - database

  # Container database
  database:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_ivsa
      - MYSQL_USER=tcc
      - MYSQL_PASSWORD=20251
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-scripts/:/docker-entrypoint-initdb.d

volumes:
  db_data: