# Utilizar a imagem Node
FROM node:lts-alpine

WORKDIR /app

# Copia somente package*.json primeiro
COPY package.json .

# Instala Angular CLI
RUN npm install -g @angular/cli

# executar processos necessarios para executar a aplicação 
RUN npm install

# Copia o restante do código
COPY . .

EXPOSE 4200
CMD ["npm", "start"]