# Utilizar a imagem Node
FROM node:lts-alpine

WORKDIR /app

# Copia somente package*.json primeiro
COPY front/package.json ./

# Instala Angular CLI
RUN npm install -g @angular/cli

# executar processos necessarios para executar a aplicação 
RUN npm install

# Copia o restante do código
COPY front/ ./

EXPOSE 4200
CMD ["npm", "start"]