FROM node:18-alpine

WORKDIR /app

# Copia somente package*.json primeiro
COPY package*.json ./

# Instala Angular CLI
RUN npm install -g @angular/cli

# Instala dependências do projeto
RUN npm install

# Copia o restante do código
COPY . .

EXPOSE 4200
CMD ["npm", "start"]